[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "app"
author = "TheOs"
author-email = "theos@tutamail.com"
home-page = "https://github.com/TheStatsProject/TheStatsProject-LMPF"
requires-python = ">=3.8"
description-file = "README.rst"
requires = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.27.1",
    "pymongo>=4.7.0",
    "python-dotenv>=1.0.0",
    "passlib[bcrypt]>=1.7.4",
    "pyjwt>=2.8.0",
    "email-validator>=2.1.0",
    "sphinx>=7.2.0",
    "jinja2>=3.1.0"
]
