[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The Truth Project"
authors = [{name = "TheOs", email = "theos@tutamail.com"}]
dynamic = ["version", "description"]
